# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    paths: ["tenants-association-be/**"]
  pull_request:
    branches: [ "main" ]
    paths: ["tenants-association-be/**"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore tenants-association-be/tenants-association-be.sln
    - name: Build
      run: dotnet build tenants-association-be/tenants-association-be.sln --no-restore
    # - name: Test
    #  run: dotnet test --no-build --verbosity normal
